### ISSUE TITLE
Support for multi line input

### ISSUE THREAD

**Issue by ashish-spext** [video-db/videodb-chat#21]
Please refer https://github.com/video-db/Director/issues/45

**Comment by tanishq3105** [comment]
@ashish-spext Please review this

**Comment by ashish-spext** [comment]
Hi @tanishq3105 thanks for the contribution!

@0xrohitgarg from our team will shortly review it.

**Comment by 0xrohitgarg** [comment]
Hi @tanishq3105, 
i have added some comments on your PR. 

https://github.com/video-db/videodb-chat/pull/24#issuecomment-2522647742

can you please check that once ?

**Comment by tanishq3105** [comment]
@0xrohitgarg please check
